### PR TITLE
Library upgrade and code cleanup

### PR DESCRIPTION
**Pull request by samcontesse**
* Upgrade go-gitlab to v0.26.0
* Upgrade gomega to v1.9.0
* Upgrade ginkgo to v1.12.0
* Make necessary changes to comply to new API
* Remove unused code
* Upgrade to Go 1.13

### CODE REVIEW

**Comment by samcontesse** [comment]
I don't have a full environment to test the resource properly. This should solve #24.

**Comment by SuperTux88** [comment]
This broke the plugin for me, and there aren't any tags with older versions pushed which makes a downgrade to the last version difficult. :(

I think it has something to do with the labels filter ... we don't have any labels set, but with the default value (`[]`) it doesn't find any MRs. Is there anything I need to set in the labels option so it finds MRs without labels now?

**Comment by SuperTux88** [comment]
OK, I just found this, it looks like it's an upstream bug with the latest go-gitlab version where it doesn't find any merge requests if you use a labels filter: https://github.com/xanzy/go-gitlab/issues/758

Can you downgrade go-gitlab to the last working version?

**Comment by samcontesse** [comment]
Sorry to hear that. I'll make my best to provide a fix quickly.

**Comment by samcontesse** [comment]
Waiting for https://github.com/xanzy/go-gitlab/pull/790 to be reviewed, merged and released

**Comment by samcontesse** [comment]
@SuperTux88 i juste created a new release which include the fix in go-gitlab concerning the labels.

**Comment by SuperTux88** [comment]
Thanks, everything works again :+1:

**Pull request merged**
